#lang racket
(require "basic-operations.rkt")
(require "mult.rkt")
(require "div.rkt")
(require "power.rkt")
(require "factorial.rkt")
(require "sum-square.rkt")
(require "sub-square.rkt")
(require "distance.rkt")